# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-31 10:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190330_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcomment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='messagecomment',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='评论内容'),
        ),
    ]
