# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0004_auto_20190531_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigcategory',
            name='description',
            field=models.TextField(default='个人网站，记录生活的喜悦，分享学习的心得', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='bigcategory',
            name='keywords',
            field=models.TextField(default='网络,IT,技术,博客,Python,猫猫,Steam', help_text='用来作为SEO中keywords,长度参考SEO标准', max_length=240, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='个人网站，记录生活的喜悦，分享学习的心得', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default='个人网站，记录生活的喜悦，分享学习的心得', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述'),
        ),
    ]
